// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2BoiVovomPaKh_7D8FJ9n0EDG1xcD50',
    appId: '1:281106816985:web:61fc80b11838f23c3dc3c8',
    messagingSenderId: '281106816985',
    projectId: 'watan-85dba',
    authDomain: 'watan-85dba.firebaseapp.com',
    storageBucket: 'watan-85dba.appspot.com',
    measurementId: 'G-KYG06GCD24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXz6m2pOWvw-_Tfgm6PSRoPJPdq-MpE2k',
    appId: '1:281106816985:android:94e2727c483458903dc3c8',
    messagingSenderId: '281106816985',
    projectId: 'watan-85dba',
    storageBucket: 'watan-85dba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvUgdvOghNgMwkjVDv8qUXis20cnai7q4',
    appId: '1:281106816985:ios:dc69ee3d64ad72f63dc3c8',
    messagingSenderId: '281106816985',
    projectId: 'watan-85dba',
    storageBucket: 'watan-85dba.appspot.com',
    iosClientId:
        '281106816985-f5c0lrvssg2h2npi1v3ihq0gm6te18ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.elwatn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvUgdvOghNgMwkjVDv8qUXis20cnai7q4',
    appId: '1:281106816985:ios:dc69ee3d64ad72f63dc3c8',
    messagingSenderId: '281106816985',
    projectId: 'watan-85dba',
    storageBucket: 'watan-85dba.appspot.com',
    iosClientId:
        '281106816985-f5c0lrvssg2h2npi1v3ihq0gm6te18ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.elwatn',
  );
}
